
services:
  mrefd:
    build:
      context: .
      dockerfile: Containerfile
    image: mrefd:latest
    container_name: mrefd
    environment:
      - TZ=${TZ:-America/Chicago}
    volumes:
      - "${CONFIG_PATH:-./mrefd.cfg}:/app/config/mrefd.cfg:ro"
      - "${BLACKLIST_PATH:-./mrefd.blacklist}:/app/config/mrefd.blacklist:ro"
      - "${WHITELIST_PATH:-./mrefd.whitelist}:/app/config/mrefd.whitelist:ro"
      - "${INTERLINK_PATH:-./mrefd.interlink}:/app/config/mrefd.interlink:ro"
      - mrefd_data:/app/data
      # - "${DHT_PATH:-./mrefd.dht.bin}:/app/config/mrefd.dht.bin" # TODO: sort out how to initialize the dht bin as part of env setup before the contrainer loads; empty file results in errors
    ports:
      - ${HOST_M17_PORT:-17000}:${CONTAINER_M17_PORT:-17000}/udp
      - ${HOST_DHT_PORT:-17171}:${CONTAINER_DHT_PORT:-17171}/udp

    restart: unless-stopped
  mrefd_dashboard:
    build:
      context: ./php-dash
      dockerfile: Containerfile
    image: mrefd-dash:latest
    depends_on:
      - mrefd
    container_name: mrefd_dashboard
    environment:
      - TZ=${TZ:-America/Chicago}
    volumes:
      - mrefd_data:/app/data
    ports:
      - ${HOST_DASHBOARD_PORT:-8080}:${CONTAINER_DASHBOARD_PORT:-80}
    restart: unless-stopped
volumes:
  mrefd_data: